version: '3.9'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --spi-theme-cors=true --spi-theme-cors-allowed-origins=*
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  keycloak-data:
